name: Publish to npm

on:
  push:
    branches: ["main"]
    paths: ["packages/cli/**", ".github/workflows/**"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: cd packages/cli && bun install

      - name: Install build
        run: cd packages/cli && bun run build

      - name: Publish to npm
        run: cd packages/cli && bun publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
